name = "tiny-urls"
main = "server/worker.ts"
compatibility_date = "2024-08-21"

[[d1_databases]]
binding = "DB"
database_name = "tiny-urls"
database_id = "a508b36b-31e5-4ad4-acd4-2b9d9220865d"

[[kv_namespaces]]
binding = "CACHE"
id = "577fe02423c74993ba05c6e1f8d6b621"
